name: Push app changes to production AWS EC2 instance

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  CreateProductionDeployment:
    runs-on: ubuntu-latest
    steps:
      # Step 1 - Clone git repository
      - name: Clone repository
        uses: actions/checkout@v3

      # Step 2 - Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.AWS_IAM_GITHUB_ACTION_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Run code deployment
      - name: Create CodeDeploy Deployment
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.AWS_CODEDEPLOY_APPLICATION_NAME }} \
            --deployment-group-name ${{ secrets.AWS_CODEDEPLOY_DEPLOYMENT_GROUP_NAME }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}